# Generated by Django 5.2.5 on 2025-12-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ArtistManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False, verbose_name='专辑ID')),
                ('album_name', models.CharField(max_length=100, verbose_name='专辑名')),
                ('release_time', models.DateField(verbose_name='发布时间')),
                ('singer_id', models.ForeignKey(db_column='album_artist_id', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='ArtistManage.artist', verbose_name='专辑歌手ID')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
                'db_table': 'album',
            },
        ),
    ]
