# Generated by Django 5.2.5 on 2025-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AlbumManage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="singer_id",
            field=models.IntegerField(
                db_column="album_artist_id", verbose_name="专辑歌手ID"
            ),
        ),
    ]
