# Generated by Django 5.2.5 on 2025-12-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ArtistManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False, verbose_name='歌曲ID')),
                ('title', models.CharField(max_length=200, verbose_name='歌曲标题')),
                ('album_id', models.IntegerField(blank=True, null=True, verbose_name='专辑ID')),
                ('duration', models.IntegerField(verbose_name='歌曲时长(秒)')),
                ('release_date', models.DateField(verbose_name='发行日期')),
                ('play_count', models.IntegerField(default=0, verbose_name='播放次数')),
                ('audio_url', models.URLField(verbose_name='音频地址')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='封面地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='ArtistManage.artist', verbose_name='所属歌手')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'db_table': 'song',
                'ordering': ['-play_count'],
            },
        ),
    ]
