# Generated by Django 5.2.5 on 2025-12-23 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ArtistManage",
            "0002_alter_artist_options_rename_name_artist_artist_name_and_more",
        ),
        ("SongManage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="cover_url",
        ),
        migrations.RemoveField(
            model_name="song",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="song",
            name="update_time",
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                db_column="artist_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ArtistManage.artist",
                verbose_name="艺术家",
            ),
        ),
    ]
