# Generated by Django 5.2.5 on 2025-12-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ArtistManage",
            "0002_alter_artist_options_rename_name_artist_artist_name_and_more",
        ),
        ("SongManage", "0002_remove_song_cover_url_remove_song_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="ArtistManage.artist",
                verbose_name="所属歌手",
            ),
        ),
    ]
