# Generated by Django 5.2.5 on 2025-12-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SongManage", "0003_alter_song_artist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"verbose_name": "歌曲", "verbose_name_plural": "歌曲"},
        ),
        migrations.RemoveField(
            model_name="song",
            name="play_count",
        ),
    ]
