# Generated by Django 5.2.5 on 2025-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SongManage", "0004_alter_song_options_remove_song_play_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.IntegerField(verbose_name="所属歌手"),
        ),
    ]
