# Generated by Django 5.2.5 on 2025-12-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SongManage", "0005_alter_song_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.IntegerField(db_column="artist_id", verbose_name="所属歌手"),
        ),
    ]
