# Generated by Django 5.2.5 on 2025-12-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False, verbose_name='歌手ID')),
                ('name', models.CharField(max_length=100, verbose_name='歌手名称')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='歌手头像')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='歌手简介')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('genre', models.CharField(blank=True, max_length=50, null=True, verbose_name='音乐风格')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '歌手',
                'verbose_name_plural': '歌手',
                'db_table': 'artist',
                'ordering': ['name'],
            },
        ),
    ]
