# Generated by Django 5.2.5 on 2025-12-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArtistManage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artist",
            options={
                "ordering": ["artist_name"],
                "verbose_name": "歌手",
                "verbose_name_plural": "歌手",
            },
        ),
        migrations.RenameField(
            model_name="artist",
            old_name="name",
            new_name="artist_name",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="introduction",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="update_time",
        ),
        migrations.AddField(
            model_name="artist",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="简介"),
        ),
        migrations.AddField(
            model_name="artist",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="地区"
            ),
        ),
    ]
