# Generated by Django 5.2.5 on 2025-12-01 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('roles', models.CharField(blank=True, default='', max_length=200)),
                ('daily_calories_burn_goal', models.IntegerField(blank=True, null=True)),
                ('daily_calories_intake_goal', models.IntegerField(blank=True, null=True)),
                ('daily_sleep_hours_goal', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'user_profile',
            },
        ),
    ]
