# Generated by Django 5.2.5 on 2025-12-01 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AlbumManage', '0001_initial'),
        ('ArtistManage', '0001_initial'),
        ('SongManage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False, verbose_name='表ID')),
                ('list_name', models.CharField(max_length=100, verbose_name='表名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='collection_lists', to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '收藏列表',
                'verbose_name_plural': '收藏列表',
                'db_table': 'collection_list',
            },
        ),
        migrations.CreateModel(
            name='CollectionListSongInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_time', models.DateTimeField(auto_now_add=True, verbose_name='收入时间')),
                ('list_id', models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, to='CollectionManage.collectionlist', verbose_name='表ID')),
                ('song_id', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='SongManage.song', verbose_name='歌曲ID')),
            ],
            options={
                'verbose_name': '收藏列表歌曲',
                'verbose_name_plural': '收藏列表歌曲',
                'db_table': 'collection_list_song_include',
                'unique_together': {('list_id', 'song_id')},
            },
        ),
        migrations.CreateModel(
            name='SingerSongPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_id', models.ForeignKey(db_column='singer_id', on_delete=django.db.models.deletion.CASCADE, to='ArtistManage.artist', verbose_name='歌手ID')),
                ('song_id', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='SongManage.song', verbose_name='歌曲ID')),
            ],
            options={
                'verbose_name': '歌手歌曲发布',
                'verbose_name_plural': '歌手歌曲发布',
                'db_table': 'singer_song_publish',
                'unique_together': {('singer_id', 'song_id')},
            },
        ),
        migrations.CreateModel(
            name='UserAlbumCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('album_id', models.ForeignKey(db_column='album_id', on_delete=django.db.models.deletion.CASCADE, to='AlbumManage.album', verbose_name='专辑ID')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户专辑收藏',
                'verbose_name_plural': '用户专辑收藏',
                'db_table': 'user_album_collect',
                'unique_together': {('user_id', 'album_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSingerFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('singer_id', models.ForeignKey(db_column='singer_id', on_delete=django.db.models.deletion.CASCADE, to='ArtistManage.artist', verbose_name='歌手ID')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户歌手关注',
                'verbose_name_plural': '用户歌手关注',
                'db_table': 'user_singer_follow',
                'unique_together': {('user_id', 'singer_id')},
            },
        ),
    ]
