# Generated by Django 5.2.5 on 2025-12-19 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlbumManage', '0001_initial'),
        ('ArtistManage', '0002_alter_artist_options_rename_name_artist_artist_name_and_more'),
        ('CollectionManage', '0001_initial'),
        ('SongManage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersingerfollow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersingerfollow',
            name='singer_id',
        ),
        migrations.RemoveField(
            model_name='usersingerfollow',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='collectionlist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='collectionlistsonginclude',
            name='include_time',
        ),
        migrations.AddField(
            model_name='collectionlistsonginclude',
            name='add_time',
            field=models.DateTimeField(db_column='ADD_TIME', default=django.utils.timezone.now, verbose_name='收入时间'),
        ),
        migrations.AlterField(
            model_name='collectionlist',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATE_TIME', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='collectionlist',
            name='list_id',
            field=models.AutoField(db_column='LIST_ID', primary_key=True, serialize=False, verbose_name='表ID'),
        ),
        migrations.AlterField(
            model_name='collectionlist',
            name='list_name',
            field=models.CharField(db_column='LIST_NAME', max_length=32, verbose_name='表名'),
        ),
        migrations.AlterField(
            model_name='collectionlistsonginclude',
            name='list_id',
            field=models.ForeignKey(db_column='LIST_ID', on_delete=django.db.models.deletion.CASCADE, to='CollectionManage.collectionlist', verbose_name='表ID'),
        ),
        migrations.AlterField(
            model_name='collectionlistsonginclude',
            name='song_id',
            field=models.ForeignKey(db_column='SONG_ID', on_delete=django.db.models.deletion.CASCADE, to='SongManage.song', verbose_name='歌曲ID'),
        ),
        migrations.AlterField(
            model_name='useralbumcollect',
            name='album_id',
            field=models.ForeignKey(db_column='ALBUM_ID', on_delete=django.db.models.deletion.CASCADE, to='AlbumManage.album', verbose_name='专辑ID'),
        ),
        migrations.AlterField(
            model_name='useralbumcollect',
            name='collect_time',
            field=models.DateTimeField(auto_now_add=True, db_column='COLLECT_TIME', verbose_name='收藏时间'),
        ),
        migrations.AlterField(
            model_name='useralbumcollect',
            name='user_id',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.AlterModelTable(
            name='collectionlist',
            table='user_favourite_songs_list',
        ),
        migrations.AlterModelTable(
            name='collectionlistsonginclude',
            table='user_song_list_relation',
        ),
        migrations.AlterModelTable(
            name='useralbumcollect',
            table='user_favourite_albums',
        ),
        migrations.CreateModel(
            name='ArtistSongPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(db_column='ARTIST_ID', on_delete=django.db.models.deletion.CASCADE, to='ArtistManage.artist', verbose_name='歌手ID')),
                ('song_id', models.ForeignKey(db_column='SONG_ID', on_delete=django.db.models.deletion.CASCADE, to='SongManage.song', verbose_name='歌曲ID')),
            ],
            options={
                'verbose_name': '歌手歌曲发布',
                'verbose_name_plural': '歌手歌曲发布',
                'db_table': 'artist_song_relation',
                'unique_together': {('artist_id', 'song_id')},
            },
        ),
        migrations.CreateModel(
            name='UserArtistFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now_add=True, db_column='FOLLOW_TIME', verbose_name='关注时间')),
                ('artist_id', models.ForeignKey(db_column='ARTIST_ID', on_delete=django.db.models.deletion.CASCADE, to='ArtistManage.artist', verbose_name='歌手ID')),
                ('user_id', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户歌手关注',
                'verbose_name_plural': '用户歌手关注',
                'db_table': 'user_follow_artists',
                'unique_together': {('user_id', 'artist_id')},
            },
        ),
        migrations.CreateModel(
            name='UserListRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.ForeignKey(db_column='LIST_ID', on_delete=django.db.models.deletion.CASCADE, to='CollectionManage.collectionlist', verbose_name='表ID')),
                ('user_id', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户收藏列表关联',
                'verbose_name_plural': '用户收藏列表关联',
                'db_table': 'user_list_relation',
                'unique_together': {('user_id', 'list_id')},
            },
        ),
        migrations.DeleteModel(
            name='SingerSongPublish',
        ),
        migrations.DeleteModel(
            name='UserSingerFollow',
        ),
    ]
