# Generated by Django 5.2.5 on 2025-12-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CollectionManage", "0002_alter_usersingerfollow_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistsongpublish",
            name="artist_id",
            field=models.IntegerField(db_column="ARTIST_ID", verbose_name="歌手ID"),
        ),
        migrations.AlterField(
            model_name="artistsongpublish",
            name="song_id",
            field=models.IntegerField(db_column="SONG_ID", verbose_name="歌曲ID"),
        ),
        migrations.AlterField(
            model_name="collectionlistsonginclude",
            name="list_id",
            field=models.IntegerField(db_column="LIST_ID", verbose_name="表ID"),
        ),
        migrations.AlterField(
            model_name="collectionlistsonginclude",
            name="song_id",
            field=models.IntegerField(db_column="SONG_ID", verbose_name="歌曲ID"),
        ),
        migrations.AlterField(
            model_name="useralbumcollect",
            name="album_id",
            field=models.IntegerField(db_column="ALBUM_ID", verbose_name="专辑ID"),
        ),
        migrations.AlterField(
            model_name="useralbumcollect",
            name="user_id",
            field=models.IntegerField(db_column="USER_ID", verbose_name="用户ID"),
        ),
        migrations.AlterField(
            model_name="userartistfollow",
            name="artist_id",
            field=models.IntegerField(db_column="ARTIST_ID", verbose_name="歌手ID"),
        ),
        migrations.AlterField(
            model_name="userartistfollow",
            name="user_id",
            field=models.IntegerField(db_column="USER_ID", verbose_name="用户ID"),
        ),
        migrations.AlterField(
            model_name="userlistrelation",
            name="list_id",
            field=models.IntegerField(db_column="LIST_ID", verbose_name="表ID"),
        ),
        migrations.AlterField(
            model_name="userlistrelation",
            name="user_id",
            field=models.IntegerField(db_column="USER_ID", verbose_name="用户ID"),
        ),
    ]
