# Generated by Django 5.2.5 on 2025-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommentManage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.AddField(
            model_name="comment",
            name="user_id",
            field=models.IntegerField(default=1, verbose_name="用户ID"),
        ),
    ]
